#!/usr/bin/env bash
# This script configures HAProxy to redirect HTTP traffic to HTTPS.

# HAProxy configuration file path
haproxy_cfg="/etc/haproxy/haproxy.cfg"

# Update HAProxy configuration for HTTP to HTTPS redirection
echo "
frontend ft_http
    bind *:80
    mode http
    option forwardfor
    option http-server-close
    option http-pretend-keepalive
    reqadd X-Forwarded-Proto:\ http
    redirect scheme https code 301 if !{ ssl_fc }

frontend ft_ssl_termination
    bind *:443 ssl crt /etc/letsencrypt/live/www.holberton.online/fullchain.pem
    reqadd X-Forwarded-Proto:\ https
    default_backend bk_web_servers

backend bk_web_servers
    server web-01 18.209.180.75:80 check
    server web-02 18.204.10.4:80 check
" | sudo tee -a "$haproxy_cfg"

# Restart HAProxy to apply changes
sudo service haproxy restart
