#!/usr/bin/env bash
# Transfer a file from client to server using scp

# Display usage if less than 4 parameters are passed
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Disable strict host key checking
scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/ 
