#!/usr/bin/env bash
# Install nginx web server on Ubuntu 16.04

# Update package list and install nginx
apt-get -y update
apt-get -y install nginx

# Configure nginx to listen on port 80
sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Restart Nginx without using systemctl
/etc/init.d/nginx restart
