#!/usr/bin/env bash

# Install Nginx
apt-get update
apt-get install nginx -y

# Start Nginx
service nginx start

# Configure Nginx to listen on port 80
sed -i 's/80 default_server/80/' /etc/nginx/sites-available/default

# Reload Nginx to apply changes
service nginx reload

# Create Hello World! index.html
echo 'Hello World!' > /usr/share/nginx/html/index.html
