#!/usr/bin/env bash
# Update package information
apt-get update

# Install Nginx
apt-get install nginx -y

# Create a new server block for redirection
echo "
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    # Additional server configuration goes here
}
" | sudo tee /etc/nginx/sites-available/redirect_me > /dev/null

# Enable the new site
ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

# Reload Nginx to apply changes
service nginx reload
