#!/usr/bin/env bash
# Update package information
apt-get update

# Install Nginx
apt-get install nginx -y

# Create a new server block for custom 404 page
echo "
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    error_page 404 /404.html;
    location = /404.html {
        root /usr/share/nginx/html;
        internal;
    }
}
" | sudo tee /etc/nginx/sites-available/custom_404 > /dev/null

# Create the custom 404 page with the desired string
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html > /dev/null

# Enable the new site
ln -s /etc/nginx/sites-available/custom_404 /etc/nginx/sites-enabled/

# Reload Nginx to apply changes
service nginx reload
