#!/usr/bin/env bash

# Function to handle SIGTERM signal
terminate() {
    echo "Terminated"
    exit
}

# Trap SIGTERM signal and call the terminate function
trap 'terminate' SIGTERM

# Main loop
while true; do
    echo "To infinity and beyond"
    sleep 2
done
