#!/usr/bin/env bash
# Get the PID of the 7-highlander process
pid=$(pgrep -f "7-highlander")

if [ -n "$pid" ]; then
    echo "Terminating process $pid"
    kill "$pid"
else
    echo "Process not found"
fi
