#!/usr/bin/env bash
# The script that displays "To infinity and beyond indefinitely" 
terminate() {
    echo "I am invincible!!!"
    exit
}

trap 'terminate' SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
