#!/usr/bin/env bash
# The script that displays "To infinity and beyond indefinitely" 
trap 'echo "I am invincible!!!"; exit' SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
