#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code and displays data

# Use awk to extract IP and HTTP status code, then count occurrences
awk '{ print $1 " " $9 }' apache-access.log | sort | uniq -c | sort -rn
