#!/usr/bin/env bash
# Displays all active IPv4 IPs

# Use ifconfig to get information about network interfaces
# Filter lines containing "inet addr:" and print the fourth field (IPv4 address)
ifconfig | awk -F "[: ]+" '/inet addr:/ { print $4 }'
