#!/usr/bin/env bash
# This script configures Nginx to run as the nginx user on port 8080 in 7 lines or less
sed -i "s/#user www-data/user ngnix/" /etc/nginx/nginx.conf
sed -i -E "s/(listen.*)80 /\18080 /g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx restart
