#!/usr/bin/env bash
# This script connects to a server using SSH with a private key

# Set the correct path to the private key
private_key_path="/root/.ssh/school"

# Replace 'your_server_ip' with the actual IP address of your server
server_ip="your_actual_server_ip"

ssh -i "$private_key_path" ubuntu@"$server_ip"
